/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Container;
import javax.swing.JPanel;
import negocio.Fachada;

/**
 *
 * @author o
 */
public class TelasProjetoFinalPrincipal extends javax.swing.JFrame {

    //Inicializar a fachada
    private Fachada fachada = new Fachada();

    private Container container;
    private JPanel jpanelTelaPrincipal;

    /**
     * Creates new form TelasProjetoFinalPrincipal /** Creates new form
     * TelasProjetoFinalPrincipal
     */
    public TelasProjetoFinalPrincipal() {
        initComponents();
        container = new Container();
        jpanelTelaPrincipal = new JPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnListarProcessos = new javax.swing.JButton();
        btnListarAvaliacoes = new javax.swing.JButton();
        btnCadastrarProcesso = new javax.swing.JButton();
        btnListarAvaliadores = new javax.swing.JButton();
        btnCadastrarAvaliadores = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemListarAvaliacoes = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Processos RSC");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bem Vindo!");

        btnListarProcessos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnListarProcessos.setText("Listar Processos");
        btnListarProcessos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarProcessosActionPerformed(evt);
            }
        });

        btnListarAvaliacoes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnListarAvaliacoes.setText("Listar Avaliações");
        btnListarAvaliacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarAvaliacoesActionPerformed(evt);
            }
        });

        btnCadastrarProcesso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCadastrarProcesso.setText("Cadastrar Processos");
        btnCadastrarProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProcessoActionPerformed(evt);
            }
        });

        btnListarAvaliadores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnListarAvaliadores.setText("Listar Avaliadores");
        btnListarAvaliadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarAvaliadoresActionPerformed(evt);
            }
        });

        btnCadastrarAvaliadores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCadastrarAvaliadores.setText("Cadastrar Avaliadores");
        btnCadastrarAvaliadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarAvaliadoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListarAvaliadores, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarAvaliadores))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListarProcessos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListarAvaliacoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCadastrarAvaliadores, btnCadastrarProcesso, btnListarAvaliacoes, btnListarAvaliadores, btnListarProcessos});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarProcessos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnListarAvaliacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCadastrarAvaliadores, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListarAvaliadores, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );

        getContentPane().add(jPanel1);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(220, 21));

        jMenu2.setText("Professores");

        jMenuItem4.setText("Listar/Pesquisar processo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem3.setText("Cadastrar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Avaliações");

        jMenuItemListarAvaliacoes.setText("Listar/Pesquisar Avaliador");
        jMenuItemListarAvaliacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarAvaliacoesActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemListarAvaliacoes);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Usuários");

        jMenuItem5.setText("Listar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem2.setText("Cadastrar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("Tela inicial");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        setJpanelTelaPrincipal(new JPanelUsuariosListar(this));
        mudarTela();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        setJpanelTelaPrincipal(jPanel1);
        mudarTela();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        setJpanelTelaPrincipal(new JPanelProcessoCadastrar(this));
        mudarTela();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        setJpanelTelaPrincipal(new JPanelUsuariosCadastrar(this));
        mudarTela();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        setJpanelTelaPrincipal(new JPanelProcessoListar(this));
        mudarTela();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItemListarAvaliacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarAvaliacoesActionPerformed
        setJpanelTelaPrincipal(new JPanelAvaliacaoListar(this));
        mudarTela();
    }//GEN-LAST:event_jMenuItemListarAvaliacoesActionPerformed

    private void btnCadastrarProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProcessoActionPerformed
        setJpanelTelaPrincipal(new JPanelProcessoCadastrar(this));
        mudarTela(); // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarProcessoActionPerformed

    private void btnListarAvaliacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarAvaliacoesActionPerformed
        setJpanelTelaPrincipal(new JPanelAvaliacaoListar(this));
        mudarTela();        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarAvaliacoesActionPerformed

    private void btnListarProcessosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarProcessosActionPerformed
        setJpanelTelaPrincipal(new JPanelProcessoListar(this));
        mudarTela();        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarProcessosActionPerformed

    private void btnListarAvaliadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarAvaliadoresActionPerformed
        setJpanelTelaPrincipal(new JPanelAvaliadorListar(this));
        mudarTela();        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarAvaliadoresActionPerformed

    private void btnCadastrarAvaliadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAvaliadoresActionPerformed
        setJpanelTelaPrincipal(new JPanelAvaliadorCadastrar(this));
        mudarTela();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarAvaliadoresActionPerformed

    // o main agora é feito pelo jframe login
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelasProjetoFinalPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelasProjetoFinalPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelasProjetoFinalPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelasProjetoFinalPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelasProjetoFinalPrincipal().setVisible(true);
//            }
//        });
//    }
    public void RetornarTelaPrincipal() {
        setJpanelTelaPrincipal(jPanel1);
        mudarTela();
    }

    public void mudarTela() {

        setContainer(getContentPane());
        getContainer().removeAll();
        getContainer().add(getJpanelTelaPrincipal());
        getContainer().repaint();
        getContainer().revalidate();
        //this.setSize(getJpanelTelaPrincipal().getPreferredSize());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarAvaliadores;
    private javax.swing.JButton btnCadastrarProcesso;
    private javax.swing.JButton btnListarAvaliacoes;
    private javax.swing.JButton btnListarAvaliadores;
    private javax.swing.JButton btnListarProcessos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemListarAvaliacoes;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the fachada
     */
    public Fachada getFachada() {
        return fachada;
    }

    /**
     * @param fachada the fachada to set
     */
    public void setFachada(Fachada fachada) {
        this.fachada = fachada;
    }

    /**
     * @return the container
     */
    public Container getContainer() {
        return container;
    }

    /**
     * @param container the container to set
     */
    public void setContainer(Container container) {
        this.container = container;
    }

    /**
     * @return the jpanelTelaPrincipal
     */
    public JPanel getJpanelTelaPrincipal() {
        return jpanelTelaPrincipal;
    }

    /**
     * @param jpanelTelaPrincipal the jpanelTelaPrincipal to set
     */
    public void setJpanelTelaPrincipal(JPanel jpanelTelaPrincipal) {
        this.jpanelTelaPrincipal = jpanelTelaPrincipal;
    }


}
